# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Study_Note\Python_code\PyQt5\ui\serial_assist_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Serial_assist_widget(object):
    def setupUi(self, Serial_assist_widget):
        Serial_assist_widget.setObjectName("Serial_assist_widget")
        Serial_assist_widget.resize(724, 464)
        self.pushButton = QtWidgets.QPushButton(Serial_assist_widget)
        self.pushButton.setGeometry(QtCore.QRect(170, 230, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Serial_assist_widget)
        QtCore.QMetaObject.connectSlotsByName(Serial_assist_widget)

    def retranslateUi(self, Serial_assist_widget):
        _translate = QtCore.QCoreApplication.translate
        Serial_assist_widget.setWindowTitle(_translate("Serial_assist_widget", "Form"))
        self.pushButton.setText(_translate("Serial_assist_widget", "PushButton"))
