# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Study_Note\Python_code\Ui\my_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyMainWindow(object):
    def setupUi(self, MyMainWindow):
        MyMainWindow.setObjectName("MyMainWindow")
        MyMainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/res/b.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MyMainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MyMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 130, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 170, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(290, 140, 61, 41))
        self.spinBox.setObjectName("spinBox")
        MyMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MyMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuedit = QtWidgets.QMenu(self.menubar)
        self.menuedit.setObjectName("menuedit")
        MyMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MyMainWindow)
        self.statusbar.setObjectName("statusbar")
        MyMainWindow.setStatusBar(self.statusbar)
        self.actionnew_file = QtWidgets.QAction(MyMainWindow)
        self.actionnew_file.setObjectName("actionnew_file")
        self.actionopen_file = QtWidgets.QAction(MyMainWindow)
        self.actionopen_file.setObjectName("actionopen_file")
        self.actionRefresh = QtWidgets.QAction(MyMainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/cartoon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon1)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionexit = QtWidgets.QAction(MyMainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menuFile.addAction(self.actionnew_file)
        self.menuFile.addAction(self.actionopen_file)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionexit)
        self.menuedit.addAction(self.actionRefresh)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuedit.menuAction())

        self.retranslateUi(MyMainWindow)
        self.pushButton.clicked.connect(self.spinBox.stepDown) # type: ignore
        self.pushButton_2.clicked.connect(self.spinBox.stepUp) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MyMainWindow)

    def retranslateUi(self, MyMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MyMainWindow.setWindowTitle(_translate("MyMainWindow", "哈哈哈"))
        self.pushButton.setText(_translate("MyMainWindow", "-"))
        self.pushButton_2.setText(_translate("MyMainWindow", "+"))
        self.menuFile.setTitle(_translate("MyMainWindow", "File"))
        self.menuedit.setTitle(_translate("MyMainWindow", "edit"))
        self.actionnew_file.setText(_translate("MyMainWindow", "new file"))
        self.actionopen_file.setText(_translate("MyMainWindow", "open file"))
        self.actionRefresh.setText(_translate("MyMainWindow", "刷新"))
        self.actionexit.setText(_translate("MyMainWindow", "exit"))
from Ui import resource_rc
